global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'smart-expense-backend'
    static_configs:
      - targets: ['backend:5000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

